<a href="https://colab.research.google.com/github/susan291-gifs/SussieAssignment/blob/main/Implementation_of_Matrix_Product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1:

To perform matrix multiplication, you take the dot product of each row of the first matrix with each column of the second matrix. Let's say we have two matrices A and B:
A = [[1,2], [3,4]]
B = [[5,6], [7,8]]
C = [[c1, c2], [c3, c4]]

c1 = (1.5) + (2.7) = 5 + 14 = 19
c2 = (1.6) + (2.8) = 6 + 16 = 22
c3 = (3.5) + (4.7) = 15 + 28 = 43
c4 = (3.6) + (4.8) = 18 + 32 = 50

So, the result of the matrix multiplication A X B is:
C = [[19, 22], [43, 50]]

Problem 2

In [ ]:
import numpy as np


A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


C_matmul = np.matmul(A, B)

C_dot = np.dot(A, B)


C_at_operator = A @ B


print("Result using np.matmul():")
print(C_matmul)

print("\nResult using np.dot():")
print(C_dot)

print("\nResult using @ operator:")
print(C_at_operator)

Result using np.matmul():
[[19 22]
 [43 50]]

Result using np.dot():
[[19 22]
 [43 50]]

Result using @ operator:
[[19 22]
 [43 50]]


Problem 3

In [ ]:
import numpy as np


A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])


rows_A, cols_A = A.shape
rows_B, cols_B = B.shape


C = np.zeros((rows_A, cols_B))


for k in range(cols_A):
    C[0, 0] += A[0, k] * B[k, 0]


print("Result at (0, 0):", C[0, 0])


Result at (0, 0): 58.0


Problem 4

In [ ]:
import numpy as np

def matrix_multiply(A,B):
  rows_A, cols_A = A.shape
  rows_B, cols_B = B.shape

  if rows_A != cols_B:
    raise ValueError("Cannot be multiply for matrix")

  C = np.zeros((rows_A, cols_B))

  for i in range(rows_A):
    for j in range(cols_B):
      for k in range(cols_A):
        C[i, j] += A[i, k] * B[k, j]

  return C

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])


result = matrix_multiply(A, B)


print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix Product (C):")
print(result)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix Product (C):
[[ 58.  64.]
 [139. 154.]]


Problem 5

In [ ]:

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
D = np.array([[1, 2], [3, 4]])
E = np.array([[5, 6, 7], [8, 9, 10]])

try:

    result = matrix_multiply(A, B)
    print("Matrix Product (A * B):")
    print(result)


    result_invalid = matrix_multiply(D, E)

except ValueError as e:
    print(f"Error: {e}")

Matrix Product (A * B):
[[ 58.  64.]
 [139. 154.]]
Error: Cannot be multiply for matrix


In [ ]:
import numpy as np

def matrix_multiply(A, B):

    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape


    if cols_A != rows_B:
        raise ValueError("Incompatible shapes for matrix multiplication. "
                         f"Number of columns in A ({cols_A}) must be equal to the number of rows in B ({rows_B}).")


    C = np.zeros((rows_A, cols_B))


    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i, j] += A[i, k] * B[k, j]

    return C

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

try:

    result = matrix_multiply(A, B)
    print("Matrix Product (A * B):")
    print(result)


    B_transposed = np.transpose(B)
    result_transposed = matrix_multiply(A, B_transposed)
    print("\nMatrix Product (A * Transpose(B)):")
    print(result_transposed)

except ValueError as e:
    print(f"Error: {e}")

Matrix Product (A * B):
[[ 58.  64.]
 [139. 154.]]
Error: Incompatible shapes for matrix multiplication. Number of columns in A (3) must be equal to the number of rows in B (2).
