<a href="https://colab.research.google.com/github/susan291-gifs/SussieAssignment/blob/main/Recurrent_Neural_Network_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

###Problem 1

In [ ]:
class ScratchSimpleRNNClassifier:
    def __init__(self, n_features, n_nodes, n_output, n_sequences, lr=0.01, random_state=None):
        np.random.seed(random_state)
        self.n_features = n_features
        self.n_nodes = n_nodes
        self.n_output = n_output
        self.n_sequences = n_sequences
        self.lr = lr

        self.Wx = np.random.randn(n_features, n_nodes)
        self.Wh = np.random.randn(n_nodes, n_nodes)
        self.B = np.zeros(n_nodes)
        self.Wout = np.random.randn(n_nodes, n_output)
        self.Bout = np.zeros(n_output)

    def forward(self, X):
        batch_size, n_sequences, n_features = X.shape
        self.h = np.zeros((batch_size, self.n_nodes))
        self.hs = np.zeros((batch_size, n_sequences, self.n_nodes))
        self.ys = np.zeros((batch_size, n_sequences, self.n_output))

        for t in range(n_sequences):
            xt = X[:, t, :]
            at = np.dot(xt, self.Wx) + np.dot(self.h, self.Wh) + self.B
            self.h = np.tanh(at)
            self.hs[:, t, :] = self.h
            self.ys[:, t, :] = self.softmax(np.dot(self.h, self.Wout) + self.Bout)

        return self.ys

    def softmax(self, x):
        exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
        return exp_x / np.sum(exp_x, axis=1, keepdims=True)

    def fit(self, X, y, epochs=10):
        for epoch in range(epochs):
            output = self.forward(X)

            pass

    def predict(self, X):
        output = self.forward(X)
        return np.argmax(output[:, -1, :], axis=1)

n_features = 4
n_nodes = 5
n_output = 3
n_sequences = 10
batch_size = 8

X = np.random.randn(batch_size, n_sequences, n_features)
y = np.random.randint(0, 3, (batch_size, n_sequences, n_output))

model = ScratchSimpleRNNClassifier(n_features, n_nodes, n_output, n_sequences)
output = model.forward(X)

print("Output shape:", output.shape)
print("Output:", output)


Output shape: (8, 10, 3)
Output: [[[0.04033645 0.28279836 0.6768652 ]
  [0.56633434 0.30114809 0.13251756]
  [0.11645023 0.2964247  0.58712507]
  [0.04350267 0.214265   0.74223233]
  [0.10644463 0.39092614 0.50262922]
  [0.64706324 0.19050295 0.16243382]
  [0.76572129 0.21152257 0.02275614]
  [0.03300119 0.07316484 0.89383398]
  [0.03140196 0.22645793 0.74214011]
  [0.13016994 0.58680999 0.28302007]]

 [[0.93301039 0.03121103 0.03577858]
  [0.63374614 0.2336149  0.13263896]
  [0.90522881 0.07166797 0.02310322]
  [0.86364632 0.06575413 0.07059955]
  [0.93603377 0.04637995 0.01758628]
  [0.73037816 0.19836454 0.07125729]
  [0.61590908 0.22345037 0.16064055]
  [0.06662899 0.13825948 0.79511153]
  [0.86763348 0.07993357 0.05243296]
  [0.20691054 0.17532395 0.61776551]]

 [[0.69878945 0.21497727 0.08623328]
  [0.52504015 0.14364724 0.33131261]
  [0.8927139  0.0794151  0.02787101]
  [0.85611288 0.10480815 0.03907897]
  [0.93587766 0.03574412 0.02837821]
  [0.71314222 0.23926227 0.04759551]
 

###Problem 2

In [ ]:
x = np.array([[[1, 2], [2, 3], [3, 4]]]) / 100
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]]) / 100
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]]) / 100
b = np.array([1, 1, 1, 1])

batch_size = x.shape[0]
n_sequences = x.shape[1]
n_features = x.shape[2]
n_nodes = w_x.shape[1]

h = np.zeros((batch_size, n_nodes))

for t in range(n_sequences):
    xt = x[:, t, :]
    at = np.dot(xt, w_x) + np.dot(h, w_h) + b
    h = np.tanh(at)

print("Final hidden state h:", h)

Final hidden state h: [[0.79494228 0.81839002 0.83939649 0.85584174]]


###Problem 3

In [ ]:
class ScratchSimpleRNNClassifier:
    def __init__(self, n_features, n_nodes, n_outputs, lr=0.01):
        self.n_features = n_features
        self.n_nodes = n_nodes
        self.n_outputs = n_outputs
        self.lr = lr

        self.W_x = np.random.randn(n_features, n_nodes)
        self.W_h = np.random.randn(n_nodes, n_nodes)
        self.b = np.zeros(n_nodes)
        self.W_y = np.random.randn(n_nodes, n_outputs)
        self.b_y = np.zeros(n_outputs)

    def forward(self, x):
        self.batch_size, self.n_sequences, self.n_features = x.shape
        self.h = np.zeros((self.batch_size, self.n_sequences + 1, self.n_nodes))

        for t in range(self.n_sequences):
            self.h[:, t + 1, :] = np.tanh(np.dot(x[:, t, :], self.W_x) + np.dot(self.h[:, t, :], self.W_h) + self.b)

        y = np.dot(self.h[:, -1, :], self.W_y) + self.b_y
        return y

    def backward(self, x, y_true, y_pred):
        dW_x = np.zeros_like(self.W_x)
        dW_h = np.zeros_like(self.W_h)
        db = np.zeros_like(self.b)
        dW_y = np.zeros_like(self.W_y)
        db_y = np.zeros_like(self.b_y)

        dy = y_pred - y_true

        dW_y = np.dot(self.h[:, -1, :].T, dy) / self.batch_size
        db_y = np.sum(dy, axis=0) / self.batch_size

        dh = np.dot(dy, self.W_y.T)

        for t in reversed(range(self.n_sequences)):
            da = dh * (1 - self.h[:, t + 1, :] ** 2)
            dW_x += np.dot(x[:, t, :].T, da) / self.batch_size
            dW_h += np.dot(self.h[:, t, :].T, da) / self.batch_size
            db += np.sum(da, axis=0) / self.batch_size

            dh = np.dot(da, self.W_h.T)

        self.W_x -= self.lr * dW_x
        self.W_h -= self.lr * dW_h
        self.b -= self.lr * db
        self.W_y -= self.lr * dW_y
        self.b_y -= self.lr * db_y

    def fit(self, X, y, epochs=10):
        for epoch in range(epochs):
            y_pred = self.forward(X)
            self.backward(X, y, y_pred)
            loss = np.mean((y_pred - y) ** 2)
            print(f'Epoch {epoch + 1}/{epochs}, Loss: {loss:.4f}')

    def predict(self, X):
        y_pred = self.forward(X)
        return y_pred


x = np.array([[[1, 2], [2, 3], [3, 4]]]) / 100
y_true = np.array([[0.5]])

model = ScratchSimpleRNNClassifier(n_features=2, n_nodes=4, n_outputs=1, lr=0.01)
model.fit(x, y_true, epochs=10)

y_pred = model.predict(x)
print("Predicted output:", y_pred)

Epoch 1/10, Loss: 0.0710
Epoch 2/10, Loss: 0.0047
Epoch 3/10, Loss: 0.0004
Epoch 4/10, Loss: 0.0000
Epoch 5/10, Loss: 0.0000
Epoch 6/10, Loss: 0.0000
Epoch 7/10, Loss: 0.0000
Epoch 8/10, Loss: 0.0000
Epoch 9/10, Loss: 0.0000
Epoch 10/10, Loss: 0.0000
Predicted output: [[0.49999884]]
